custom:
  host: ${HOST|"localhost"}
  database:
    url: postgresql://${custom.host}:5432/prison_break_game

spring:
  application:
    name: prision-break-game
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${custom.database.url}
  r2dbc:
    url: r2dbc:${custom.database.url}
    username: ${DB_USER|"admin"}
    password: ${DB_PASSWORD|"admin"}
  flyway:
    url: jdbc:${custom.database.url}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    enabled: true
    baseline-on-migrate: true

springdoc:
  version: 1.0.0
  api-docs:
    groups:
      enabled: true
    path: /prison-break-game-doc/v3/api-docs
  swagger-ui:
    path: /prison-break-game-doc/swagger-ui.html

server:
  servlet:
    context-path: /
  error:
    include-message: always
